source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'GeoFeatures-iOS', :exclusive => true do
  platform :ios, '8.0'
  
  pod "GeoFeatures", :path => "../"
end

target 'GeoFeatures-iOS-Tests', :exclusive => true do
  platform :ios, '8.0'
  
  pod "GeoFeatures", :path => "../"
end
