source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GeoFeatures2_Example', :exclusive => true do
  pod 'GeoFeatures2', :path => '../'
end

target 'GeoFeatures2_Tests', :exclusive => true do
  pod 'GeoFeatures2', :path => '../'

  
end
