var searchData=
[
  ['geometryatindex_3a',['geometryAtIndex:',['../interface_g_f_geometry_collection.html#aa4a654ef8751bdf8abac169f8746d026',1,'GFGeometryCollection']]],
  ['geometrywithgeojsongeometry_3a',['geometryWithGeoJSONGeometry:',['../category_g_f_geometry_07_geo_j_s_o_n_08.html#afcdd23bd5dd4b04868d6baf577f9bb32',1,'GFGeometry(GeoJSON)::geometryWithGeoJSONGeometry:()'],['../interface_g_f_geometry.html#afcdd23bd5dd4b04868d6baf577f9bb32',1,'GFGeometry::geometryWithGeoJSONGeometry:()']]],
  ['geometrywithwkt_3a',['geometryWithWKT:',['../category_g_f_geometry_07_w_k_t_08.html#a26ad5ae365b4dd4847fdb3370dfb6bb2',1,'GFGeometry(WKT)::geometryWithWKT:()'],['../interface_g_f_geometry.html#a26ad5ae365b4dd4847fdb3370dfb6bb2',1,'GFGeometry::geometryWithWKT:()']]],
  ['gfbox',['GFBox',['../interface_g_f_box.html',1,'']]],
  ['gfgeometry',['GFGeometry',['../interface_g_f_geometry.html',1,'']]],
  ['gfgeometry_28geojson_29',['GFGeometry(GeoJSON)',['../category_g_f_geometry_07_geo_j_s_o_n_08.html',1,'']]],
  ['gfgeometry_28mapkit_29',['GFGeometry(MapKit)',['../category_g_f_geometry_07_map_kit_08.html',1,'']]],
  ['gfgeometry_28wkt_29',['GFGeometry(WKT)',['../category_g_f_geometry_07_w_k_t_08.html',1,'']]],
  ['gfgeometrycollection',['GFGeometryCollection',['../interface_g_f_geometry_collection.html',1,'']]],
  ['gflinestring',['GFLineString',['../interface_g_f_line_string.html',1,'']]],
  ['gflinestringabstract',['GFLineStringAbstract',['../interface_g_f_line_string_abstract.html',1,'']]],
  ['gfmultilinestring',['GFMultiLineString',['../interface_g_f_multi_line_string.html',1,'']]],
  ['gfmultipoint',['GFMultiPoint',['../interface_g_f_multi_point.html',1,'']]],
  ['gfmultipolygon',['GFMultiPolygon',['../interface_g_f_multi_polygon.html',1,'']]],
  ['gfpoint',['GFPoint',['../interface_g_f_point.html',1,'']]],
  ['gfpointabstract',['GFPointAbstract',['../interface_g_f_point_abstract.html',1,'']]],
  ['gfpolygon',['GFPolygon',['../interface_g_f_polygon.html',1,'']]],
  ['gfpolygonabstract',['GFPolygonAbstract',['../interface_g_f_polygon_abstract.html',1,'']]]
];
