///
/// AVLTreeTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension AVLTreeTests {

   static var allTests: [(String, (AVLTreeTests) -> () throws -> Void)] {
      return [
                ("testLeftRotation", testLeftRotation),
                ("testRightRotation", testRightRotation),
                ("testLeftRightRotation", testLeftRightRotation),
                ("testRightLeftRotation", testRightLeftRotation),
                ("testHeightEmptyTree", testHeightEmptyTree),
                ("testHeight", testHeight),
                ("testBalancedEmptyTree", testBalancedEmptyTree),
                ("testBalanced9NodeTree", testBalanced9NodeTree),
                ("testBalanced1NodeTree", testBalanced1NodeTree),
                ("testBalanced2NodeTree", testBalanced2NodeTree),
                ("testBalanced3NodeRightHeavyTree", testBalanced3NodeRightHeavyTree),
                ("testHeight3NodeRightHeavyTree", testHeight3NodeRightHeavyTree),
                ("testBalanced3NodeLeftHeavyTree", testBalanced3NodeLeftHeavyTree),
                ("testHeight3NodeLeftHeavyTree", testHeight3NodeLeftHeavyTree),
                ("testBalanced3NodeLeftRightHeavyTree", testBalanced3NodeLeftRightHeavyTree),
                ("testHeight3NodeLeftRightHeavyTree", testHeight3NodeLeftRightHeavyTree),
                ("testBalanced3NodeOrderedTree", testBalanced3NodeOrderedTree),
                ("testInsertNonExisting30", testInsertNonExisting30),
                ("testInsertLeftA", testInsertLeftA),
                ("testInsertLeftnegative1", testInsertLeftnegative1),
                ("testInsertExisting8", testInsertExisting8),
                ("testDeleteNonExisting30", testDeleteNonExisting30),
                ("testDeleteRoot1NodeTree", testDeleteRoot1NodeTree),
                ("testDeleteRoot3NodeTree", testDeleteRoot3NodeTree),
                ("testDeleteExisting1", testDeleteExisting1),
                ("testDeleteExisting5", testDeleteExisting5),
                ("testDeleteExisting7", testDeleteExisting7),
                ("testDeleteExisting8", testDeleteExisting8),
                ("testDeleteExisting10", testDeleteExisting10),
                ("testDeleteExistingLeafNodesForceReBalance", testDeleteExistingLeafNodesForceReBalance),
                ("testDeleteExistingLeafNodesNoReBalance", testDeleteExistingLeafNodesNoReBalance),
                ("testDeleteExistingInnerNodes", testDeleteExistingInnerNodes),
                ("testDeleteExistingSingleLeftNode", testDeleteExistingSingleLeftNode),
                ("testDeleteExistingAllBut3", testDeleteExistingAllBut3),
                ("testDeleteExistingAllBut1", testDeleteExistingAllBut1),
                ("testDeleteExistingAll", testDeleteExistingAll),
                ("testSearchExisting1", testSearchExisting1),
                ("testSearchExisting8", testSearchExisting8),
                ("testSearchExisting25", testSearchExisting25),
                ("testSearchNonExisting0", testSearchNonExisting0),
                ("testSearchNonExisting30", testSearchNonExisting30),
                ("testNextOf1", testNextOf1),
                ("testNextOf7", testNextOf7),
                ("testNextOf8", testNextOf8),
                ("testNextOf10", testNextOf10),
                ("testNextOf15", testNextOf15),
                ("testNextOf25", testNextOf25),
                ("testPreviousOf1", testPreviousOf1),
                ("testPreviousOf8", testPreviousOf8),
                ("testPreviousOf10", testPreviousOf10),
                ("testPreviousOf15", testPreviousOf15),
                ("testPreviousOf17", testPreviousOf17),
                ("testSearchPerformance", testSearchPerformance),
                ("testInsertPerformance", testInsertPerformance),
                ("testDeletePerformance", testDeletePerformance)
           ]
   }
}
