///
/// GeometryCollection+GeometryTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension GeometryCollection_Geometry_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (GeometryCollection_Geometry_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
                ("testDimension_Homogeneous_Point", testDimension_Homogeneous_Point),
                ("testDimension_Homogeneous_LineString", testDimension_Homogeneous_LineString),
                ("testDimension_Homogeneous_Polygon", testDimension_Homogeneous_Polygon),
                ("testDimension_Non_Homogeneous_Point_Polygon", testDimension_Non_Homogeneous_Point_Polygon),
                ("testDimension_Non_Homogeneous_Point_LineString", testDimension_Non_Homogeneous_Point_LineString),
                ("testBoundary", testBoundary),
                ("testEqual_True", testEqual_True),
                ("testEqual_SameTypes_False", testEqual_SameTypes_False),
                ("testEqual_DifferentTypes_False", testEqual_DifferentTypes_False)
           ]
   }
}
extension GeometryCollection_Geometry_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (GeometryCollection_Geometry_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
                ("testDimension_Homogeneous_Point", testDimension_Homogeneous_Point),
                ("testDimension_Homogeneous_LineString", testDimension_Homogeneous_LineString),
                ("testDimension_Homogeneous_Polygon", testDimension_Homogeneous_Polygon),
                ("testDimension_Non_Homogeneous_Point_Polygon", testDimension_Non_Homogeneous_Point_Polygon),
                ("testDimension_Non_Homogeneous_Point_LineString", testDimension_Non_Homogeneous_Point_LineString)
           ]
   }
}
