///
/// LineStringTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension LineStringCoordinate2DFloatingPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate2DFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineStringCoordinate2DMFloatingPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate2DMFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineStringCoordinate3DFloatingPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate3DFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineStringCoordinate3DMFloatingPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate3DMFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineStringCoordinate2DFixedPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate2DFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineStringCoordinate2DMFixedPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate2DMFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineStringCoordinate3DFixedPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate3DFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineStringCoordinate3DMFixedPrecisionCartesianTests {

   static var allTests: [(String, (LineStringCoordinate3DMFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testInitWithPrecisionAndCRS", testInitWithPrecisionAndCRS),
                ("testInitWithPrecision", testInitWithPrecision),
                ("testInitWithCRS", testInitWithCRS),
                ("testInitWithTuple", testInitWithTuple),
                ("testInitCopy", testInitCopy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppendContentsOf", testAppendContentsOf),
                ("testAppendContentsOfCoordinates", testAppendContentsOfCoordinates),
                ("testAppendContentsOfWithTuples", testAppendContentsOfWithTuples),
                ("testInsertCoordinate", testInsertCoordinate),
                ("testInsertTuple", testInsertTuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAllKeepingCapacity", testRemoveAllKeepingCapacity),
                ("testSubscriptGet", testSubscriptGet),
                ("testSubscriptSet", testSubscriptSet),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmptyFalse", testIsEmptyFalse),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
