///
/// LineStringTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension LineString_Coordinate2D_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate2D_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineString_Coordinate2DM_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate2DM_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineString_Coordinate3D_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate3D_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineString_Coordinate3DM_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate3DM_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineString_Coordinate2D_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate2D_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineString_Coordinate2DM_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate2DM_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineString_Coordinate3D_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate3D_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
extension LineString_Coordinate3DM_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Coordinate3DM_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testInit_Precision_CRS", testInit_Precision_CRS),
                ("testInit_Precision", testInit_Precision),
                ("testInit_CRS", testInit_CRS),
                ("testInit_Tuple", testInit_Tuple),
                ("testInit_Copy", testInit_Copy),
                ("testDescription", testDescription),
                ("testDebugDescription", testDebugDescription),
                ("testReserveCapacity", testReserveCapacity),
                ("testAppend", testAppend),
                ("testAppend_ContentsOf", testAppend_ContentsOf),
                ("testAppend_ContentsOf_Coordinates", testAppend_ContentsOf_Coordinates),
                ("testAppend_ContentsOf_Tuples", testAppend_ContentsOf_Tuples),
                ("testInsert_Coordinate", testInsert_Coordinate),
                ("testInsert_Tuple", testInsert_Tuple),
                ("testRemove", testRemove),
                ("testRemoveLast", testRemoveLast),
                ("testRemoveAll", testRemoveAll),
                ("testRemoveAll_KeepCapacity", testRemoveAll_KeepCapacity),
                ("testSubscript_Get", testSubscript_Get),
                ("testSubscript_Set", testSubscript_Set),
                ("testEquals", testEquals),
                ("testIsEmpty", testIsEmpty),
                ("testIsEmpty_False", testIsEmpty_False),
                ("testCount", testCount),
                ("testEnsureUniquelyReferenced", testEnsureUniquelyReferenced),
                ("testResizeIfNeeded", testResizeIfNeeded)
           ]
   }
}
