///
/// MultiLineString+GeometryTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension MultiLineStringGeometryCoordinate2DFloatingPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate2DFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
                ("testBoundaryWith1ElementInvalid", testBoundaryWith1ElementInvalid),
                ("testBoundaryWith2Element", testBoundaryWith2Element),
                ("testBoundaryWith3ElementOpen", testBoundaryWith3ElementOpen),
                ("testBoundaryWith4ElementClosed", testBoundaryWith4ElementClosed),
                ("testBoundaryWith2EqualPoints", testBoundaryWith2EqualPoints),
                ("testBoundaryEmpty", testBoundaryEmpty),
                ("testBoundaryWithOGCMultiCurveA", testBoundaryWithOGCMultiCurveA),
                ("testBoundaryWithOGCMultiCurveB", testBoundaryWithOGCMultiCurveB),
                ("testBoundaryWithOGCMultiCurveC", testBoundaryWithOGCMultiCurveC),
                ("testBoundaryWithOddIntersection", testBoundaryWithOddIntersection),
                ("testEqualTrue", testEqualTrue),
                ("testEqualFalse", testEqualFalse)
           ]
   }
}
extension MultiLineStringGeometryCoordinate2DMFloatingPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate2DMFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension MultiLineStringGeometryCoordinate3DFloatingPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate3DFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension MultiLineStringGeometryCoordinate3DMFloatingPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate3DMFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension MultiLineStringGeometryCoordinate2DFixedPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate2DFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension MultiLineStringGeometryCoordinate2DMFixedPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate2DMFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension MultiLineStringGeometryCoordinate3DFixedPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate3DFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension MultiLineStringGeometryCoordinate3DMFixedPrecisionCartesianTests {

   static var allTests: [(String, (MultiLineStringGeometryCoordinate3DMFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
