/*
 *   MultiPointTests.swift
 *
 *   Copyright 2016 Tony Stone
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 *   Created by Tony Stone on 3/6/16.
 */
import XCTest

import GeoFeatures

/*
    NOTE: This file was auto generated by gyb from file MultiPointTests.swift.gyb using the following command.

../bin/gyb --line-directive '' -DGeometryType=MultiPoint -DFileName=MultiPoint.swift -o MultiPointTests.swift MultiPointTests.swift.gyb

    Do NOT edit this file directly as it will be regenerated automatically when needed.
*/

// MARK: - Coordinate2D, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate2D_FloatingPrecision_Cartesian_Tests : XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)),Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate2D>, rhs: Point<Coordinate2D>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.0, y: 1.0))
        
        XCTAssertEqual(geometry[1], Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)),Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate2D>, rhs: Point<Coordinate2D>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))]

        geometry.append(Point(coordinate: (x: 1.0, y: 1.0)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate2D>, rhs: Point<Coordinate2D>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.0, y: 1.0)),Point(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}

// MARK: - Coordinate2DM, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate2DM_FloatingPrecision_Cartesian_Tests : XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate2DM>, rhs: Point<Coordinate2DM>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.0, y: 1.0, m: 1.0))
        
        XCTAssertEqual(geometry[1], Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate2DM>, rhs: Point<Coordinate2DM>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))]

        geometry.append(Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate2DM>, rhs: Point<Coordinate2DM>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}

// MARK: - Coordinate3D, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate3D_FloatingPrecision_Cartesian_Tests : XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate3D>, rhs: Point<Coordinate3D>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.0, y: 1.0, z: 1.0))
        
        XCTAssertEqual(geometry[1], Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate3D>, rhs: Point<Coordinate3D>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))]

        geometry.append(Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate3D>, rhs: Point<Coordinate3D>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}

// MARK: - Coordinate3DM, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate3DM_FloatingPrecision_Cartesian_Tests : XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate3DM>, rhs: Point<Coordinate3DM>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))
        
        XCTAssertEqual(geometry[1], Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate3DM>, rhs: Point<Coordinate3DM>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))]

        geometry.append(Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate3DM>, rhs: Point<Coordinate3DM>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}

// MARK: - Coordinate2D, FixedPrecision, Cartesian -

class MultiPoint_Coordinate2D_FixedPrecision_Cartesian_Tests : XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)),Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate2D>, rhs: Point<Coordinate2D>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.001, y: 1.001))
        
        XCTAssertEqual(geometry[1], Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)),Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate2D>, rhs: Point<Coordinate2D>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))]

        geometry.append(Point(coordinate: (x: 1.001, y: 1.001)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate2D>, rhs: Point<Coordinate2D>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate2D>(elements: [Point(coordinate: (x: 1.001, y: 1.001)),Point(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}

// MARK: - Coordinate2DM, FixedPrecision, Cartesian -

class MultiPoint_Coordinate2DM_FixedPrecision_Cartesian_Tests : XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate2DM>, rhs: Point<Coordinate2DM>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.001, y: 1.001, m: 1.001))
        
        XCTAssertEqual(geometry[1], Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)),Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate2DM>, rhs: Point<Coordinate2DM>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))]

        geometry.append(Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate2DM>, rhs: Point<Coordinate2DM>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate2DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}

// MARK: - Coordinate3D, FixedPrecision, Cartesian -

class MultiPoint_Coordinate3D_FixedPrecision_Cartesian_Tests : XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate3D>, rhs: Point<Coordinate3D>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.001, y: 1.001, z: 1.001))
        
        XCTAssertEqual(geometry[1], Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)),Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate3D>, rhs: Point<Coordinate3D>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))]

        geometry.append(Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate3D>, rhs: Point<Coordinate3D>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate3D>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}

// MARK: - Coordinate3DM, FixedPrecision, Cartesian -

class MultiPoint_Coordinate3DM_FixedPrecision_Cartesian_Tests : XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    func testInit_NoArg ()   {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }
    
    func testInit_Tuple () {
        let geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        XCTAssertTrue(
            (geometry.elementsEqual(expected)
                { (lhs: Point<Coordinate3DM>, rhs: Point<Coordinate3DM>) -> Bool in
                    return lhs == rhs
            }
        ), "\(geometry) is not equal to \(expected)")
    }

    func testSubscript_Get () {
        let geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        XCTAssertEqual(geometry[1], Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)))
    }
    
    func testSubscript_Set () {
        var geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        
        geometry[1] = Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001))
        
        XCTAssertEqual(geometry[1], Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)))
    }
    
    func testAppend_MultiPoint () {
        
        let geometry1 = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var geometry2 = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        
        geometry2.append(contentsOf: geometry1)
        
        XCTAssertEqual(geometry1, geometry2)
    }
    
    func testAppend_Array () {
        
        var geometry = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)),Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        geometry.append(contentsOf: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))])
        
        XCTAssertTrue(geometry.elementsEqual(expected) { (lhs: Point<Coordinate3DM>, rhs: Point<Coordinate3DM>) -> Bool in
            return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testEquals () {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs).equals(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)), true)
    }

    func testIsEmpty () {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs).count, 2)
    }
    
    func testAppend () {
        var geometry = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))]

        geometry.append(Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)))
        
        XCTAssertTrue(geometry.elementsEqual(expected)
            { (lhs: Point<Coordinate3DM>, rhs: Point<Coordinate3DM>) -> Bool in
                return lhs == rhs
        }, "\(geometry) is not equal to \(expected)")
    }

    func testRemoveAll () {
        var geometry = MultiPoint<Coordinate3DM>(elements: [Point(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)),Point(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }
}
