/*
 *   MultiPointTests.swift
 *
 *   Copyright 2016 Tony Stone
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 *   Created by Tony Stone on 3/6/16.
 */
import XCTest

import GeoFeatures

/*
    NOTE: This file was auto generated by gyb from file MulitGeometryTests.swift.gyb using the following command.

    ../bin/gyb --line-directive '' -DConfiguration='MultiPointTests' -o MultiPointTests.swift MultiPointTests.swift.gyb

    Do NOT edit this file directly as it will be regenerated automatically when needed.
*/
// MARK: - Coordinate2D, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate2D_FloatingPrecision_Cartesian_Tests: XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).precision as? FloatingPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision).precision as? FloatingPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2D>(Point<Coordinate2D>(x: 1.0, y: 1.0), Point<Coordinate2D>(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2D>(Point<Coordinate2D>(x: 1.0, y: 1.0), Point<Coordinate2D>(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))]

        input.append(Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)), Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        input.insert(Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)), Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))]

        input.insert(Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
// MARK: - Coordinate2DM, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate2DM_FloatingPrecision_Cartesian_Tests: XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).precision as? FloatingPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision).precision as? FloatingPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2DM>(Point<Coordinate2DM>(x: 1.0, y: 1.0, m: 1.0), Point<Coordinate2DM>(x: 2.0, y: 2.0, m: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2DM>(Point<Coordinate2DM>(x: 1.0, y: 1.0, m: 1.0), Point<Coordinate2DM>(x: 2.0, y: 2.0, m: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))]

        input.append(Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)), Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        input.insert(Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)), Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))]

        input.insert(Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
// MARK: - Coordinate3D, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate3D_FloatingPrecision_Cartesian_Tests: XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).precision as? FloatingPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision).precision as? FloatingPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3D>(Point<Coordinate3D>(x: 1.0, y: 1.0, z: 1.0), Point<Coordinate3D>(x: 2.0, y: 2.0, z: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3D>(Point<Coordinate3D>(x: 1.0, y: 1.0, z: 1.0), Point<Coordinate3D>(x: 2.0, y: 2.0, z: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))]

        input.append(Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)), Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        input.insert(Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)), Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))]

        input.insert(Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
// MARK: - Coordinate3DM, FloatingPrecision, Cartesian -

class MultiPoint_Coordinate3DM_FloatingPrecision_Cartesian_Tests: XCTestCase {

    let precision = FloatingPrecision()
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).precision as? FloatingPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision).precision as? FloatingPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3DM>(Point<Coordinate3DM>(x: 1.0, y: 1.0, z: 1.0, m: 1.0), Point<Coordinate3DM>(x: 2.0, y: 2.0, z: 2.0, m: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3DM>(Point<Coordinate3DM>(x: 1.0, y: 1.0, z: 1.0, m: 1.0), Point<Coordinate3DM>(x: 2.0, y: 2.0, z: 2.0, m: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))]

        input.append(Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)), Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        input.insert(Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)), Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))]

        input.insert(Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
// MARK: - Coordinate2D, FixedPrecision, Cartesian -

class MultiPoint_Coordinate2D_FixedPrecision_Cartesian_Tests: XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).precision as? FixedPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(precision: precision).precision as? FixedPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2D>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2D>(Point<Coordinate2D>(x: 1.0, y: 1.0), Point<Coordinate2D>(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2D>(Point<Coordinate2D>(x: 1.0, y: 1.0), Point<Coordinate2D>(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))]

        input.append(Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)), Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))]

        input.insert(Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0)), Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))]

        input.insert(Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.0, y: 1.0)), Point<Coordinate2D>(coordinate: (x: 2.0, y: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate2D>(elements: [Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)), Point<Coordinate2D>(coordinate: (x: 2.002, y: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate2D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate2D>(coordinate: (x: 1.001, y: 1.001)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
// MARK: - Coordinate2DM, FixedPrecision, Cartesian -

class MultiPoint_Coordinate2DM_FixedPrecision_Cartesian_Tests: XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).precision as? FixedPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(precision: precision).precision as? FixedPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate2DM>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2DM>(Point<Coordinate2DM>(x: 1.0, y: 1.0, m: 1.0), Point<Coordinate2DM>(x: 2.0, y: 2.0, m: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate2DM>(Point<Coordinate2DM>(x: 1.0, y: 1.0, m: 1.0), Point<Coordinate2DM>(x: 2.0, y: 2.0, m: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))]

        input.append(Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)), Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))]

        input.insert(Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0)), Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))]

        input.insert(Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.0, y: 1.0, m: 1.0)), Point<Coordinate2DM>(coordinate: (x: 2.0, y: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate2DM>(elements: [Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)), Point<Coordinate2DM>(coordinate: (x: 2.002, y: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate2DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate2DM>(coordinate: (x: 1.001, y: 1.001, m: 1.001)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
// MARK: - Coordinate3D, FixedPrecision, Cartesian -

class MultiPoint_Coordinate3D_FixedPrecision_Cartesian_Tests: XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).precision as? FixedPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(precision: precision).precision as? FixedPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3D>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3D>(Point<Coordinate3D>(x: 1.0, y: 1.0, z: 1.0), Point<Coordinate3D>(x: 2.0, y: 2.0, z: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3D>(Point<Coordinate3D>(x: 1.0, y: 1.0, z: 1.0), Point<Coordinate3D>(x: 2.0, y: 2.0, z: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))]

        input.append(Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)), Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))]

        input.insert(Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0)), Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))]

        input.insert(Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.0, y: 1.0, z: 1.0)), Point<Coordinate3D>(coordinate: (x: 2.0, y: 2.0, z: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate3D>(elements: [Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)), Point<Coordinate3D>(coordinate: (x: 2.002, y: 2.002, z: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate3D>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate3D>(coordinate: (x: 1.001, y: 1.001, z: 1.001)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
// MARK: - Coordinate3DM, FixedPrecision, Cartesian -

class MultiPoint_Coordinate3DM_FixedPrecision_Cartesian_Tests: XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let crs       = Cartesian()

    // MARK: Construction

    func testInit_NoArg() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).isEmpty, true)
    }

    func testInit_Precision_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).precision as? FixedPrecision, precision)
        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Precision() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(precision: precision).precision as? FixedPrecision, precision)
    }

    func testInit_CRS() {

        XCTAssertEqual(MultiPoint<Coordinate3DM>(coordinateReferenceSystem: crs).coordinateReferenceSystem as? Cartesian, crs)
    }

    func testInit_Tuple() {

        let input = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        XCTAssertTrue(
            (input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                    return lhs == rhs
            }
        ), "\(input) is not equal to \(expected)")
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3DM>(Point<Coordinate3DM>(x: 1.0, y: 1.0, z: 1.0, m: 1.0), Point<Coordinate3DM>(x: 2.0, y: 2.0, z: 2.0, m: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = "MultiPoint<Coordinate3DM>(Point<Coordinate3DM>(x: 1.0, y: 1.0, z: 1.0, m: 1.0), Point<Coordinate3DM>(x: 2.0, y: 2.0, z: 2.0, m: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance

    func testReserveCapacity() {

        var input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testAppend() {

        var input    = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))]

        input.append(Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)))

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
        }, "\(input) is not equal to \(expected)")
    }

    func testAppend_ContentsOf() {

        let input1 = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        var input2 = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }

    func testInsert_2ExistingElements() {

        var input = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)), Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]

        input.insert(Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testInsert_1ExistingElements() {

        var input = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001))], precision: precision, coordinateReferenceSystem: crs)
        let expected = [Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)), Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))]

        input.insert(Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002)), at: 0)

        XCTAssertTrue(input.elementsEqual(expected) { (lhs: MultiPoint.Element, rhs: MultiPoint.Element) -> Bool in
                return lhs == rhs
            }, "\(input) is not equal to \(expected)")
    }

    func testRemove() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.remove(at: 0)

        XCTAssertEqual(input, expected)
    }

    func testRemoveLast() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        let _ = input.removeLast()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected =  MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)

        input.removeAll()

        XCTAssertEqual(input, expected)
    }

    func testRemoveAll_KeepCapacity() {

        var input =  MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity

        input.removeAll(keepingCapacity: true)

        XCTAssertEqual(input.capacity, expected)
    }

    // MARK: Swift.Collection Conformance

    func testSubscript_Get() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscript_Set() {

        var input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))], precision: precision, coordinateReferenceSystem: crs)

        input[1] = Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001))

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Point<Coordinate3DM>(coordinate: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: precision, coordinateReferenceSystem: crs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmpty_False() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint<Coordinate3DM>(elements: [Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)), Point<Coordinate3DM>(coordinate: (x: 2.002, y: 2.002, z: 2.002, m: 2.002))], precision: precision, coordinateReferenceSystem: crs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }

    // MARK: Misc Internal

    func testEnsureUniquelyReferenced() {

        var input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        let copy = input    // This should force the reserveCapacity to clone
        let _ = copy.capacity

        input.reserveCapacity(expected)

        XCTAssertEqual(input.capacity, expected)
    }

    func testResizeIfNeeded() {

        var input = MultiPoint<Coordinate3DM>(precision: precision, coordinateReferenceSystem: crs)
        let expected = input.capacity * 2

        // Force it beyond its initial capacity
        for _ in 0..<input.capacity + 1 {
            input.append(Point<Coordinate3DM>(coordinate: (x: 1.001, y: 1.001, z: 1.001, m: 1.001)))
        }
        XCTAssertEqual(input.capacity, expected)
    }
}
