///
/// Polygon+GeometryTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension PolygonGeometryCoordinate2DFloatingPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate2DFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
                ("testBoundaryWithOuterRing", testBoundaryWithOuterRing),
                ("testBoundaryWithOuterRingAnd1InnerRing", testBoundaryWithOuterRingAnd1InnerRing),
                ("testBoundaryEmpty", testBoundaryEmpty),
                ("testEqualTrue", testEqualTrue),
                ("testEqualFalse", testEqualFalse)
           ]
   }
}
extension PolygonGeometryCoordinate2DMFloatingPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate2DMFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension PolygonGeometryCoordinate3DFloatingPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate3DFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension PolygonGeometryCoordinate3DMFloatingPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate3DMFloatingPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension PolygonGeometryCoordinate2DFixedPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate2DFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension PolygonGeometryCoordinate2DMFixedPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate2DMFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension PolygonGeometryCoordinate3DFixedPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate3DFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
extension PolygonGeometryCoordinate3DMFixedPrecisionCartesianTests {

   static var allTests: [(String, (PolygonGeometryCoordinate3DMFixedPrecisionCartesianTests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension)
           ]
   }
}
