///
/// WKTReaderTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension WKTReader_Coordinate2D_FloatingPrecision_Cartesian_Tests {

   static var allTests : [(String, (WKTReader_Coordinate2D_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testRead_Point_Float_Valid", testRead_Point_Float_Valid),
                ("testRead_Point_Int_Valid", testRead_Point_Int_Valid),
                ("testRead_Point_Invalid_WhiteSpace", testRead_Point_Invalid_WhiteSpace),
                ("testRead_Point_Valid_Exponent_UpperCase", testRead_Point_Valid_Exponent_UpperCase),
                ("testRead_Point_Valid_Exponent_LowerCase", testRead_Point_Valid_Exponent_LowerCase),
                ("testRead_Point_InvalidCoordinate", testRead_Point_InvalidCoordinate),
                ("testRead_LineString_Valid", testRead_LineString_Valid),
                ("testRead_MultiPoint_Valid", testRead_MultiPoint_Valid),
                ("testRead_MultiPoint_Invalid_MissingClosingParen", testRead_MultiPoint_Invalid_MissingClosingParen),
                ("testRead_MultiLineString_Valid", testRead_MultiLineString_Valid),
                ("testRead_MultiLineString_Invalid_MissingCLosingParen", testRead_MultiLineString_Invalid_MissingCLosingParen),
                ("testRead_Polygon_ZeroInnerRings_Valid", testRead_Polygon_ZeroInnerRings_Valid),
                ("testRead_Polygon_SingleOuterRing_Valid", testRead_Polygon_SingleOuterRing_Valid),
                ("testRead_Polygon_MultipleOuterRings_Valid", testRead_Polygon_MultipleOuterRings_Valid),
                ("testRead_Polygon_MultipleOuterRings_Invalid_MissingComma", testRead_Polygon_MultipleOuterRings_Invalid_MissingComma),
                ("testRead_MultiPolygon_Valid", testRead_MultiPolygon_Valid),
                ("testRead_GeometryCollection_Valid", testRead_GeometryCollection_Valid),
                ("testReadPerformance_Polygon_California", testReadPerformance_Polygon_California),
           ]
   }
}

