/*
*   LineStringCoordinate3DMFloatingPrecisionTests.swift
 *
 *   Copyright 2016 Tony Stone
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 *   Created by Tony Stone on 2/10/16.
 */
import XCTest
@testable import GeoFeatures2

/*
    NOTE: This file was auto generated by gyb from file CoordinateCollectionTests.swift.gyb using the following command.

    ~/gyb --line-directive '' -DCoordinateType=Coordinate3DM -D"TestTuple0=(x: 1.0, y: 1.0, z: 1.0, m: 1.0)" -D"TestTuple1=(x: 2.0, y: 2.0, z: 2.0, m: 2.0)" -D"ExpectedTuple0=(x: 1.0, y: 1.0, z: 1.0, m: 1.0)" -D"ExpectedTuple1=(x: 2.0, y: 2.0, z: 2.0, m: 2.0)" -D"Precision=FloatingPrecision()" -DGeometryType=LineString -o LineStringCoordinate3DMFloatingPrecisionTests.swift CoordinateCollectionTests.swift.gyb

    Do NOT edit this file directly as it will be regenerated automatically when needed.
*/

class LineStringCoordinate3DMFloatingPrecisionTests : XCTestCase {

    // MARK: Init
    
    func testInit_NoArg ()   {
        XCTAssertEqual(LineString<Coordinate3DM>(precision: FloatingPrecision()).isEmpty, true)
    }
    
    func testInit_Tuple () {
    
        XCTAssertEqual(
            (LineString<Coordinate3DM>(elements: [(x: 1.0, y: 1.0, z: 1.0, m: 1.0),(x: 2.0, y: 2.0, z: 2.0, m: 2.0)], precision: FloatingPrecision()).elementsEqual([Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))])
                { (lhs: Coordinate3DM, rhs: Coordinate3DM) -> Bool in
                    return lhs == rhs
            }
        ), true)
    }
    
    // MARK: CollectionType
    
    func testSubscript_Get () {
        let geometry = LineString<Coordinate3DM>(elements: [(x: 1.0, y: 1.0, z: 1.0, m: 1.0),(x: 2.0, y: 2.0, z: 2.0, m: 2.0)], precision: FloatingPrecision())
        
        XCTAssertEqual(geometry[1] == Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0)), true)
    }
    
    func testSubscript_Set () {
        var geometry = LineString<Coordinate3DM>(elements: [(x: 1.0, y: 1.0, z: 1.0, m: 1.0),(x: 2.0, y: 2.0, z: 2.0, m: 2.0)], precision: FloatingPrecision())
        
        geometry[1] = Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))
        
        XCTAssertEqual(geometry[1] ==  Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), true)
    }
    
    func testAppendContentsOf_LineString () {
        
        let geometry1 = LineString<Coordinate3DM>(elements: [(x: 1.0, y: 1.0, z: 1.0, m: 1.0),(x: 2.0, y: 2.0, z: 2.0, m: 2.0)], precision: FloatingPrecision())
        var geometry2 = LineString<Coordinate3DM>(precision: FloatingPrecision())
        
        geometry2.appendContentsOf(geometry1)
        
        XCTAssertEqual(geometry1 == geometry2, true)
    }
    
    func testAppendContentsOf_Array () {
        
        var geometry = LineString<Coordinate3DM>(precision: FloatingPrecision())
        
        geometry.appendContentsOf([Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))])
        
        XCTAssertEqual(geometry.elementsEqual([Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))]) { (lhs: Coordinate3DM, rhs: Coordinate3DM) -> Bool in
            return lhs == rhs
        }, true)
    }
    
    // MARK: Equal
    
    func testEquals () {
        XCTAssertEqual(LineString<Coordinate3DM>(elements: [Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: FloatingPrecision()).equals(LineString<Coordinate3DM>(elements: [Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: FloatingPrecision())), true)
    }
    
    // MARK: isEmpty
    
    func testIsEmpty () {
        XCTAssertEqual(LineString<Coordinate3DM>(precision: FloatingPrecision()).isEmpty(), true)
    }
    
    func testIsEmpty_False() {
        XCTAssertEqual(LineString<Coordinate3DM>(elements: [Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: FloatingPrecision()).isEmpty(), false)
    }
    
    func testCount () {
        XCTAssertEqual(LineString<Coordinate3DM>(elements: [Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: FloatingPrecision()).count, 2)
    }
    
    func testAppend () {
        var geometry = LineString<Coordinate3DM>(precision: FloatingPrecision())
        
        geometry.append((x: 1.0, y: 1.0, z: 1.0, m: 1.0))
        
        XCTAssertEqual(geometry.elementsEqual([Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0))])
            { (lhs: Coordinate3DM, rhs: Coordinate3DM) -> Bool in
                return lhs == rhs
        }, true)
    }

    func testRemoveAll () {
        var geometry = LineString<Coordinate3DM>(elements: [Coordinate3DM(tuple: (x: 1.0, y: 1.0, z: 1.0, m: 1.0)), Coordinate3DM(tuple: (x: 2.0, y: 2.0, z: 2.0, m: 2.0))], precision: FloatingPrecision())

        geometry.removeAll()

        XCTAssertEqual(geometry.isEmpty(), true)
    }

}
